NAME = 'bibi'
VERSION = 0.1


def parse_file(filename):
	fin = open(filename)
	bib = {}
	entry = ''
	key = ''
	for line in fin:
	    if line.startswith('@'):
	        # begin
	        entry = line
	        key = line[line.find('{')+1:line.find(',')]
	    elif line=='}\n':
	        entry += line
	        bib[key] = entry
	        key = ''
	        line = ''
	    else:
	        entry += line
	fin.close()
	return bib


def to_file(filename, bib, keys):
	fout = open(filename, 'w')
	fout.write("Automatically generated by %s %s\n" % (NAME, VERSION))
	fout.write("Any changes to this file will be lost if it is regenerated by %s.\n\n" % NAME)
	for k in keys:
		entry = bib[k]
		fout.write(entry)
	fout.close()


def to_string(bib, keys):
	string = ''
	for k in keys:
		string += bib[k]
	return string


if __name__ == '__main__':
	bib = parse_file(r'd:\library.bib')
	to_file('tmp.bib', bib, ['Altenberg2011', 'Gavrilets2003', 'Gordo2005'])
	print to_string(bib, ['Ram2012'])